// Code generated by buf. DO NOT EDIT.
// Run: make generate
// Source: api/proto/entity/v1/entity.proto

package entityv1

import (
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// Entity represents a domain entity (generated from proto).
type Entity struct {
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

// GetEntityRequest is the request for GetEntity (generated from proto).
type GetEntityRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

// CreateEntityRequest is the request for CreateEntity (generated from proto).
type CreateEntityRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}
