// Code generated by buf. DO NOT EDIT.
// Run: make generate
// Source: api/proto/entity/v1/entity.proto

package entityv1

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// EntityServiceServer is the server API for EntityService (generated from proto).
// All implementations must embed UnimplementedEntityServiceServer.
type EntityServiceServer interface {
	GetEntity(context.Context, *GetEntityRequest) (*Entity, error)
	CreateEntity(context.Context, *CreateEntityRequest) (*Entity, error)
	mustEmbedUnimplementedEntityServiceServer()
}

// UnimplementedEntityServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEntityServiceServer struct{}

func (UnimplementedEntityServiceServer) GetEntity(context.Context, *GetEntityRequest) (*Entity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntity not implemented")
}
func (UnimplementedEntityServiceServer) CreateEntity(context.Context, *CreateEntityRequest) (*Entity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEntity not implemented")
}
func (UnimplementedEntityServiceServer) mustEmbedUnimplementedEntityServiceServer() {}

// RegisterEntityServiceServer registers the EntityServiceServer with the gRPC server.
func RegisterEntityServiceServer(s grpc.ServiceRegistrar, srv EntityServiceServer) {
	s.RegisterService(&EntityService_ServiceDesc, srv)
}

// EntityService_ServiceDesc is the grpc.ServiceDesc for EntityService.
var EntityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "entity.v1.EntityService",
	HandlerType: (*EntityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "GetEntity", Handler: _EntityService_GetEntity_Handler},
		{MethodName: "CreateEntity", Handler: _EntityService_CreateEntity_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entity/v1/entity.proto",
}

func _EntityService_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/entity.v1.EntityService/GetEntity"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).GetEntity(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_CreateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).CreateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/entity.v1.EntityService/CreateEntity"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).CreateEntity(ctx, req.(*CreateEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}
